### ISSUE TITLE
 no such element: Unable to locate element: {"method":"xpath","selector":"//input[@type='file']"}

### ISSUE THREAD

**Issue by RedGeneral-X** [wkaisertexas/tiktok-uploader#53]
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@type='file']"}
  (Session info: chrome=117.0.5938.92); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x0063CEB3+45171]
        (No symbol) [0x005C9101]
        (No symbol) [0x004BBE1D]
        (No symbol) [0x004EED40]
        (No symbol) [0x004EF20B]
        (No symbol) [0x0051F692]
        (No symbol) [0x0050B094]
        (No symbol) [0x0051DCFA]
        (No symbol) [0x0050AE46]
        (No symbol) [0x004E675E]
        (No symbol) [0x004E78FD]
        GetHandleVerifier [0x008F54B9+2897529]
        GetHandleVerifier [0x0093DC6B+3194411]
        GetHandleVerifier [0x00937A41+3169281]
        GetHandleVerifier [0x006C6130+606960]
        (No symbol) [0x005D2E7C]
        (No symbol) [0x005CF008]
        (No symbol) [0x005CF12F]
        (No symbol) [0x005C1827]
        BaseThreadInitThunk [0x76A4FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77667B1E+286]
        RtlGetAppContainerNamedObjectPath [0x77667AEE+238]

**Comment by RedGeneral-X** [comment]
Guys Hellp !

**Comment by RedGeneral-X** [comment]
Any idea how to fix ???


C:\Users\vboxuser\Desktop\tiktok-uploader-main>tiktok-uploader -v video.mov -d "this is my escaped \"description\"" -c cookies.txt
[23:11:59] ←[92mAuthenticating browser with cookies←[0m
[23:11:59] Create a chrome browser instance in headless mode

DevTools listening on ws://127.0.0.1:54319/devtools/browser/525722a0-3c63-43d2-8d93-54946da23d95
[23:12:07] Authenticating browser with cookies
[7384:5244:0927/231219.478:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105
[7384:5244:0927/231220.716:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105
[23:12:23] Posting video.mov
               with description: this is my escaped "description"
[23:12:23] Navigating to upload page
[7384:5244:0927/231228.701:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105
[7384:5244:0927/231229.308:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105
[23:13:28] Failed to upload C:\Users\vboxuser\Desktop\tiktok-uploader-main\video.mov
[23:13:28] Message:
Stacktrace:
        GetHandleVerifier [0x00ECCEB3+45171]
        (No symbol) [0x00E59101]
        (No symbol) [0x00D4BE1D]
        (No symbol) [0x00D7ED40]
        (No symbol) [0x00D7F20B]
        (No symbol) [0x00DAF692]
        (No symbol) [0x00D9B094]
        (No symbol) [0x00DADCFA]
        (No symbol) [0x00D9AE46]
        (No symbol) [0x00D7675E]
        (No symbol) [0x00D778FD]
        GetHandleVerifier [0x011854B9+2897529]
        GetHandleVerifier [0x011CDC6B+3194411]
        GetHandleVerifier [0x011C7A41+3169281]
        GetHandleVerifier [0x00F56130+606960]
        (No symbol) [0x00E62E7C]
        (No symbol) [0x00E5F008]
        (No symbol) [0x00E5F12F]
        (No symbol) [0x00E51827]
        BaseThreadInitThunk [0x75F9FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77337B1E+286]
        RtlGetAppContainerNamedObjectPath [0x77337AEE+238]

-------------------------
Error while uploading video

**Comment by nausibo** [comment]
I have the same, did you fixed it ?

**Comment by RedGeneral-X** [comment]
Still not fixed !!!

**Comment by splitzzzzz** [comment]
fixed?

**Comment by nausibo** [comment]
> fixed?

Nop

**Comment by deploy010101** [comment]
Hello @wkaisertexas, it seems that the upload link has been updated in the repo code, but when installing the package via pip this change doesn't seem to be reflected there.

**Comment by deploy010101** [comment]
@aliensz https://github.com/wkaisertexas/tiktok-uploader#building-from-source

**Comment by aliensz** [comment]
> @aliensz https://github.com/wkaisertexas/tiktok-uploader#building-from-source

Weird. I've tried that and I still get "No module named tiktok_uploader". I honestly don't know what to do

**Comment by libinghui123** [comment]
same error

**Comment by zegeree** [comment]
> I think the solution is to navigate to `tiktok_uploader/config.toml` file and update the upload link to : `upload = "https://www.tiktok.com/creator-center/upload"`

Even when changing this in the program it will still output the same error... Im willing to pay you some money if you could help me on this or if anyone else could. I tried contacting the owner but hes most likely busy. Lmk, contact on "Zeger.vg@gmail.com" or discord "Zeger#2971"

**Comment by XavierZambrano** [comment]
https://github.com/wkaisertexas/tiktok-uploader/pull/71
